vich_uploader:
    db_driver: orm

    mappings:
        avatar_image:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        object_image:
            uri_prefix: '/images/'
            upload_destination:   '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_remove: true
            delete_on_update: true
