<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGNGUnSY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGNGUnSY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGNGUnSY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGNGUnSY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGNGUnSY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GNGUnSY',
    'container.build_id' => '4ce8fd95',
    'container.build_time' => 1598096432,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGNGUnSY');
