<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container19iEyWT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container19iEyWT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container19iEyWT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container19iEyWT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container19iEyWT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '19iEyWT',
    'container.build_id' => '7d3917c6',
    'container.build_time' => 1578839589,
], __DIR__.\DIRECTORY_SEPARATOR.'Container19iEyWT');
