/*
export const ACCUEIL_SHOW_ALL = 'ACCUEIL_SHOW_ALL'
export const ACCUEIL_SHOW_COMPLETED = 'ACCUEIL_SHOW_COMPLETED'
export const ACCUEIL_SHOW_ACTIVE = 'ACCUEIL_SHOW_ACTIVE'
*/

export const ACCUEIL_SHOW_ALL 		= 'ACCUEIL_SHOW_ALL'
export const ACCUEIL_SHOW_METEO 	= 'ACCUEIL_SHOW_METEO'
export const ACCUEIL_SHOW_AFFAIRE 	= 'ACCUEIL_SHOW_AFFAIRE'
export const ACCUEIL_SHOW_TALENT 	= 'ACCUEIL_SHOW_TALENT'
export const ACCUEIL_SHOW_CALENDAR 	= 'ACCUEIL_SHOW_CALENDAR'
export const ACCUEIL_SHOW_BASIC 	= 'ACCUEIL_SHOW_BASIC'